#include<stdio.h>
int main()
{
    int arr[4]={};
    for(int i=0;i<4;i++)
    {
        scanf("%d",&arr[i]);
    }
for (int i=0;i<4;i++)
{
    printf("%d\n",arr[i]);
}
}
2.addition in array
#include<stdio.h>
int main()
{
    int arr[]={2,2,2,2,2};
    int sum=0;
    for(int i=0;i<5;i++)
    {
        scanf("%d",&arr[i]);
        }
        for(int i=0;i<5;i++)
        {
            sum+=arr[i];
            
        }
        printf("%d",sum);
        return 0;
    }

3.
